### ISSUE TITLE
sdfsdfsdfsdf

### ISSUE THREAD

**Issue by eidoloerp** [eidoloerp/mis#1]
```yaml
start_date: 2022/06/22
due_date: 2022/06/24
progress: 0
parent: 
```

sfsdfsdfsdfsfdsdf
