### ISSUE TITLE
hjgjgfjh

### ISSUE THREAD

**Issue by eidoloerp** [eidoloerp/mis#2]
```yaml
start_date: 2022/10/17
due_date: 2022/10/27
progress: 0
parent: 
```

nmvbnmvbnmvbnm
