### ISSUE TITLE
Miki Job

### ISSUE THREAD

**Issue by eidoloerp** [eidoloerp/mis#3]
```yaml
start_date: 2022/06/13
due_date: 2022/07/01
progress: 0
parent: 
```

Hacer software
