### ISSUE TITLE
Gabi Job

### ISSUE THREAD

**Issue by eidoloerp** [eidoloerp/mis#4]
```yaml
start_date: 2022/06/13
due_date: 2022/06/30
progress: 0
parent: 
```

Software
