### ISSUE TITLE
Gabi

### ISSUE THREAD

**Issue by eidoloerp** [eidoloerp/mis#5]
```yaml
start_date: 2022/06/11
due_date: 2022/06/21
progress: 0
parent: 
```

Gabi Desc
