### ISSUE TITLE
Miki

### ISSUE THREAD

**Issue by eidoloerp** [eidoloerp/mis#6]
```yaml
start_date: 2022/06/02
due_date: 2022/06/16
progress: 0
parent: 
```

Miki Desc
